### ISSUE TITLE
Issue in path

### ISSUE THREAD

**Issue by nineRishav** [DocF/multispectral-object-detection#41]
Namespace(augment=False, batch_size=64, conf_thres=0.001, data='/home/delll/mark1/multispectral-object-detection/data/multispectral/FLIR_aligned.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.5, name='exp', project='runs/test', save_conf=True, save_hybrid=False, save_json=False, save_txt=True, single_cls=False, task='val', verbose=False, weights='/home/delll/mark1/multispectral-object-detection/best.pt')
/home/delll/mark1/multispectral-object-detection/data/multispectral/FLIR_aligned.yaml
YOLOv5 🚀 387dc3e torch 1.13.0+cu117 CPU

Fusing layers... 
Model Summary: 1015 layers, 206209480 parameters, 0 gradients
val
Traceback (most recent call last):
  File "/home/delll/mark1/multispectral-object-detection/utils/datasets.py", line 875, in __init__
    raise Exception(f'{prefix}{path_rgb} does not exist')
Exception: val: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 339, in <module>
    opt=opt
  File "test.py", line 94, in test
    prefix=colorstr(f'{task}: '))[0]
  File "/home/delll/mark1/multispectral-object-detection/utils/datasets.py", line 236, in create_dataloader_rgb_ir
    prefix=prefix)
  File "/home/delll/mark1/multispectral-object-detection/utils/datasets.py", line 899, in __init__
    raise Exception(f'{prefix}Error loading data from {path_rgb,path_ir}: {e}\nSee {help_url}')
Exception: val: Error loading data from ('/home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt', '/home/fqy/Data/FLIR_ADAS_1_3/align/yolo/ir/align_validation.txt'): val: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt does not exist
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

**Comment by DocF** [comment]
U should change the yaml file------------------ Original ------------------From: Rishav KUMAR  ***@***.***>Date: Mon,Oct 31,2022 8:21 PMTo: DocF/multispectral-object-detection ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [DocF/multispectral-object-detection] Issue in path (Issue #41)
Namespace(augment=False, batch_size=64, conf_thres=0.001, data='/home/delll/mark1/multispectral-object-detection/data/multispectral/FLIR_aligned.yaml', device='', exist_ok=False, img_size=640, iou_thres=0.5, name='exp', project='runs/test', save_conf=True, save_hybrid=False, save_json=False, save_txt=True, single_cls=False, task='val', verbose=False, weights='/home/delll/mark1/multispectral-object-detection/best.pt')
/home/delll/mark1/multispectral-object-detection/data/multispectral/FLIR_aligned.yaml
YOLOv5 🚀 387dc3e torch 1.13.0+cu117 CPU
Fusing layers...
Model Summary: 1015 layers, 206209480 parameters, 0 gradients
val
Traceback (most recent call last):
File "/home/delll/mark1/multispectral-object-detection/utils/datasets.py", line 875, in init
raise Exception(f'{prefix}{path_rgb} does not exist')
Exception: val: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt does not exist
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "test.py", line 339, in 
opt=opt
File "test.py", line 94, in test
prefix=colorstr(f'{task}: '))[0]
File "/home/delll/mark1/multispectral-object-detection/utils/datasets.py", line 236, in create_dataloader_rgb_ir
prefix=prefix)
File "/home/delll/mark1/multispectral-object-detection/utils/datasets.py", line 899, in init
raise Exception(f'{prefix}Error loading data from {path_rgb,path_ir}: {e}\nSee {help_url}')
Exception: val: Error loading data from ('/home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt', '/home/fqy/Data/FLIR_ADAS_1_3/align/yolo/ir/align_validation.txt'): val: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt does not exist
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DocF/multispectral-object-detection/issues/41",
"url": "https://github.com/DocF/multispectral-object-detection/issues/41",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
