### ISSUE TITLE
关于训练文件缺失的问题

### ISSUE THREAD

**Issue by 116508** [DocF/multispectral-object-detection#5]
Traceback (most recent call last):
  File "/home/fhl/src/rgbt-det/multispectral-object-detection/train.py", line 1028, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "/home/fhl/src/rgbt-det/multispectral-object-detection/train.py", line 519, in train_rgb_ir
    model = Model(opt.cfg or ckpt['model'].yaml, ch=6, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/fhl/src/rgbt-det/multispectral-object-detection/models/yolo_test.py", line 188, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/fhl/src/rgbt-det/multispectral-object-detection/models/yolo_test.py", line 529, in parse_model
    elif m is CMAFF:
NameError: name 'CMAFF' is not defined

在common.py文件中发现CMAFF未定义,请问是什么原因导致的?

**Comment by DocF** [comment]
谢谢你的提醒，CMAFF其实是我另一篇论文的模型，这里不小心放进来了。
过段时间我会清理一遍代码，以确保此类问题不再发生。

**Comment by 116508** [comment]
非常感谢你的回复，你的开源工作将给我带来巨大的帮助，谢谢

**Comment by wlc-git** [comment]
How do you do? May I ask why CLS is always 0 when I train

**Comment by DocF** [comment]
> 非常感谢你的回复，你的开源工作将给我带来巨大的帮助，谢谢
已经清理了代码，并进行了提交。

**Comment by DocF** [comment]
> 非常感谢你的回复，你的开源工作将给我带来巨大的帮助，谢谢

已经清理一遍代码并提交，你可以使用当前版本的代码进行训练、测试。
